/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Picture Taker
 #	author : miyako
 #	2017/06/19
 #
 # --------------------------------------------------------------------------------*/

#include "libjson.h"

#import <Quartz/Quartz.h>

// --- Picture Taker
void DISPLAY_PICTURE_TAKER(sLONG_PTR *pResult, PackagePtr pParams);
